name : CI MLflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL: "Project/wine-quality.csv"
  TARGET_VAR: "quality"
  ALPHA: 0.5
  L1_RATIO: 0.5
  RANDOM_STATE: 42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout your repo under $github_workspace
      - uses: actions/checkout@v3

      # setup python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # check env variabel
      - name: Check env
        run: |
          echo $CSV_URL

      # install mlflow
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # run as administrator
      - name: Run mlflow project
        run: |
          mlflow run Project --env-manager=local
        




      
